# Generated by Django 5.2.5 on 2025-12-25 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='برند')),
                ('url_title', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='دسته بندی')),
                ('url_title', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': ' رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='سایز/حجم')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر')),
                ('short_description', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product_module.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(related_name='product_category', to='product_module.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product-gallery', verbose_name='توصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': ' گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن نظر')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید توسط ادمین ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_module.products', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name': 'نظرات محصول ',
                'verbose_name_plural': 'نظرات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='آی پی کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدیدهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product-variant', verbose_name='تصویر')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_module.products', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.size')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انوع محصول',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
