# Generated by Django 5.2.5 on 2026-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_brand_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='brand',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_fa',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_fa',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_en',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_fa',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='size',
            name='name_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='سایز/حجم'),
        ),
        migrations.AddField(
            model_name='size',
            name='name_fa',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='سایز/حجم'),
        ),
    ]
