# Generated by Django 5.2.5 on 2025-12-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان بنر')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس بنر ')),
                ('image', models.ImageField(upload_to='sitebanner/', verbose_name='تصویر بنر ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزئیات محصولات'), ('article_page', 'صفحه مقالات')], max_length=300, verbose_name='جایگاه نمایشی ')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
            },
        ),
        migrations.CreateModel(
            name='Sitsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sit_name', models.CharField(max_length=100, verbose_name='اسم سایت')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='شعار')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sit_images/', verbose_name='لوگو')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('copyright', models.TextField(blank=True, null=True, verbose_name='حق کپی رایت ')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='آیدی اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='آیدی تلگرام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.URLField(max_length=100, verbose_name='لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/ غیرفعال بودن')),
            ],
            options={
                'verbose_name': 'اسلایدر ',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
