# Generated by Django 5.2.5 on 2025-12-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitsetting_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='position',
        ),
    ]
