# Generated by Django 5.2.5 on 2025-12-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitsetting_module', '0002_remove_banners_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='url_title',
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='لینک'),
        ),
    ]
