# Generated by Django 5.2.5 on 2026-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitsetting_module', '0003_remove_slider_description_remove_slider_url_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitsetting',
            name='Sit_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم سایت'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='Sit_name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم سایت'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='about_us_en',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='about_us_fa',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='address_fa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شعار'),
        ),
        migrations.AddField(
            model_name='sitsetting',
            name='slogan_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شعار'),
        ),
    ]
