# Generated by Django 5.2.5 on 2026-01-07 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
        ('product_module', '0002_alter_brand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productvariant', verbose_name='محصول'),
        ),
    ]
