# Generated by Django 5.2.5 on 2025-10-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
        migrations.AddField(
            model_name='brand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, null=False, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
