# Generated by Django 5.2.5 on 2025-10-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_products_brand_alter_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
