# Generated by Django 5.2.5 on 2025-10-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_images_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-gallery', verbose_name='توصویر'),
        ),
    ]
