# Generated by Django 5.2.5 on 2025-10-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_productgallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.AddField(
            model_name='productgallery',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.attribute', verbose_name='رنگ مربوط'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='سایز/حجم')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalue', to='product_module.attribute', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'سایز/حجم',
                'verbose_name_plural': 'سایزها/حجم ها',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت مخصوص این ترکیب')),
                ('attribute', models.ManyToManyField(to='product_module.attributevalue', verbose_name='این چی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_module.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cهای محصول',
            },
        ),
    ]
