# Generated by Django 5.2.5 on 2025-10-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_alter_category_options_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='parent',
        ),
    ]
