# Generated by Django 5.2.5 on 2025-11-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_remove_productcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
