# Generated by Django 5.2.5 on 2025-11-16 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_color_size_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='color',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product-variant', verbose_name='توصویر')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product_module.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product_module.size')),
            ],
            options={
                'verbose_name': 'تنوع',
                'verbose_name_plural': 'تنوعات',
            },
        ),
    ]
