# Generated by Django 5.2.5 on 2025-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_remove_products_size_remove_size_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': ' گالری تصویر', 'verbose_name_plural': ' گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': 'انوع محصول'},
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد محصول'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-gallery', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-variant', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='سایز/حجم'),
        ),
    ]
