# Generated by Django 5.2.5 on 2026-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_fa',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان مقاله '),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان مقاله '),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان دسته بندی '),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان دسته بندی '),
        ),
    ]
